# -*- coding: utf-8 -*-
"""labcycle1: 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YxkwclkLXfvFpaonwVt_Y9HfMGTp1i4v
"""

#1. Develop a program to read a four-digit number and find its
# a. Sum of digits
# b. Reverse
# c. Difference between the product of digits at the odd position
# and the product of digits at the even position

num1 = int(input("enter a four digit number : "))#input from user
units=num1%10# to get units digit
num1=num1//10
tens=num1%10# to get tens digit
num1=num1//10
hunds=num1%10#  to get hundreds digit
num1=num1//10
thous=num1%10# to get thousands digits
sum1=units+tens+hunds+thous # sum of digits
rev=units*1000+tens*100+hunds*10+thous # reverse of number
sum2=thous*tens-hunds*units# c in question

print(sum1)#sum of digits
print(rev)# reverse
print(sum2)