# -*- coding: utf-8 -*-
"""labcycle1: 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V5Oxln-G0FpGxW7WF_69dEAd229ZGmIV
"""

# Develop a program to read the three sides of two triangles and
# calculate the area of both. Define a function to read the three sides
# and call it. Also, define a function to calculate the area. Print the total
# area enclosed by both triangles and each triangle's contribution (%)
# towards it
def intake():# taking sides of triangle  from user
  a= float(input("enter side 1 "))
  b= float(input("enter side 2 "))
  c= float(input("enter side 3 "))
  s= (a+b+c)/2
  return a,b,c,s
def area():# function to calculate area
  a,b,c,s= intake()
  ar= (s*(s-a)*(s-b)*(s-c))**0.5
  return ar

print("triangle 1: ")# printing total area and contribution of each triangle
ar1=area()
print("triangle 2: ")
ar2=area()
print("total area: ",ar1+ar2,)
print("contribution of triangle 1 = ",ar1/(ar1+ar2)*100,"%")
print("contribution of triangle 2 = ",ar2/(ar1+ar2)*100,"%")