# -*- coding: utf-8 -*-
"""labcycle1: 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YL-ecZ-WuFyFKkpf-uX4phs4DeY2AW1H
"""

#Develop a program to read a string and perform the following operations:
# • Print all possible substrings.
# • Print all possible substrings of length K.
# • Print all possible substrings of length K with N distinct characters.
# • Print substring(s) of length maximum length with N distinct characters.
# • Print all palindrome substrings.


st=str(input("enter any string: "))  # getting a string as input
def sub_str1(): # function to print all substrings
  for i in range(0,len(st)+1):
    for j in range(i+1,len(st)+1):
      s=st[i:j]
      print(s)

def sub_str2():# function to print all substrings of a specific
  k= int(input("enter the length of substring: "))
  for i in range(0,len(st)+1):
    for j in range(i+1,len(st)+1):
      s=st[i:j]
      if(len(s)==k):
       print(s)

def sub_str3(): # function to print all substings of specific distinct character and length
  k= int(input("enter the length of substring: "))
  n= int(input("enter the number of distinct characters: "))
  for i in range(0,len(st)+1):
    for j in range(i+1,len(st)+1):
      s=st[i:j]
    if(len(s)==k and len(set(s))==n):
       print(s)

def sub_str4(): # fuction to print longest string with specific distinct charcters
  l=[]
  n= int(input("enter the number of distinct characters"))
  for i in range(0,len(st)+1):
    for j in range(i+1,len(st)+1):
      s=st[i:j]
      if(len(set(s))==n):
       l.append(s)
  m=len(max(l,key=len))
  for i in range(len(l)):
    if(len(l[i])==m):
      print(l[i])


def sub_str5():# to check if palindrome or not
  for i in range(0,len(st)+1):
    for j in range(i+1,len(st)+1):
      s=st[i:j]
      temp=s[::-1]
      if(s==temp):
        print(s)
  


print("all substrings")        
sub_str1()
print("all substrings with specific length" )
sub_str2()
print("all substrings with specific length and distinct terms" )
sub_str3()
print("all substrings with specific distinct number and maximum length" )
sub_str4()
print("all the palindromes")
sub_str5()