# -*- coding: utf-8 -*-
"""labcycle2: 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12sGJbV0JckePLxcIWuuJa4j_rt1DOt_l
"""

# Read the file 'iris.json' as a text file :
#     1. Create a list having each line of the file as an element
#     2. Convert it into a list of dictionary objects.
#     3. Show the details of all flowers whose species is "setosa".
#     4. Print the minimum petal area and max sepal area in each species
#     5. Sort the list of dictionaries according to the total area are sepal and petal.

#reading the file iris.json as a text file
j=open("iris.json","r")

#list with each line of the file as an element
list1=j.readlines()
# print(list1)

# list of dictionary objects
j=open("iris.json","r")
import json
list2= json.load(j)
j.close()
n=len(list2)

print("                  Details of specie setosa")
print("                 --------------------------  ")
print("    Sepal Length     Sepal Width     Petal Length     Petal Width")
# details of flowers of setosa specie
for i in list2:
  if i["species"]=="setosa":
   print("\t",i['sepalLength'],"\t\t",i['sepalWidth'],"\t\t",i['petalLength'],"\t\t",i['petalWidth'])

#  minimum petal area and max sepal area each species
listSet1= []
listSet2= []
for i in list2:
  if i["species"]=="setosa":
    listSet1.append(i["petalLength"]*i["petalWidth"])
    listSet2.append(i["sepalLength"]*i["sepalWidth"])

listVer1= []
listVer2= []
for i in list2:
  if i["species"]=="versicolor":
    listVer1.append(i["petalLength"]*i["petalWidth"])
    listVer2.append(i["sepalLength"]*i["sepalWidth"])
    
listVir1= []
listVir2= []
for i in list2:
  if i["species"]=="virginica":
    listVir1.append(i["petalLength"]*i["petalWidth"])
    listVir2.append(i["sepalLength"]*i["sepalWidth"])

print(" ")
print("The minimum petal area in setosa = ",min(listSet1))
print("The maximum sepal area in setosa = ",max(listSet2))
print(" ")
print("The minimum petal area in versicolor = ",min(listVer1))
print("The maximum sepal area in versicolor = ",max(listVer2))
print(" ")
print("The minimum petal area in virginica = ",min(listVir1))
print("The maximum sepal area in virginica = ",max(listVir2))
print(" ")

#sorting list of dictionaries based on total area
list3= []
for i in list2:
  i["totalArea"]=(i["petalLength"]*i["petalWidth"]+i["sepalLength"]*i["sepalWidth"])
  list3.append(i["totalArea"])

set1=set(list3)
list3=list(set1)
list3.sort()

list5=[]
for i in range (0,len(list3)):
 for j in list2:
  if list3[i]==j["totalArea"]:
    list5.append(j)
list2=list5

#for checking the sorted list
# for i in range(0,len(list2)):
#  print(list2[i])